#!/usr/bin/env bash
# Configure custom Nginx response header to track HTTP requests to web servers
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart#!/usr/bin/env bash
# Configure custom Nginx response header to track HTTP requests to web servers
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart#!/usr/bin/env bash
# Configure custom Nginx response header to track HTTP requests to web servers
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart#!/usr/bin/env bash
# Configure custom Nginx response header to track HTTP requests to web servers
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart#!/usr/bin/env bash
# Configure custom Nginx response header to track HTTP requests to web servers
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart#!/usr/bin/env bash
# Configure custom Nginx response header to track HTTP requests to web servers
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart#!/usr/bin/env bash
# Configure custom Nginx response header to track HTTP requests to web servers
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart
